server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_1122
    username: root
    password: root
  application:
    name: spring_provider
mybatis:
  type-aliases-package: com.zxy.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10087/eureka
